### ISSUE TITLE
Fix Layout Website 

### ISSUE THREAD

**Issue by TaiTitans** [TaiTitans/porscher_website#1]
Css Navbar :
![image](https://github.com/TaiTitans/TaiTitans.github.io/assets/70010376/43c470d7-2b2b-4710-8bd9-468b2aafdc03)

center between components at index.html , lienlac.html, gioithieu.html : 
![image](https://github.com/TaiTitans/TaiTitans.github.io/assets/70010376/1a94a73c-9ab6-4f27-9aa0-bfc369d026f4)

![image](https://github.com/TaiTitans/TaiTitans.github.io/assets/70010376/f5a749e6-d6b0-4d1a-b100-172e42feb01f)

![image](https://github.com/TaiTitans/TaiTitans.github.io/assets/70010376/14be241e-6a33-4980-8122-0ff7bac91584)

Fix footer Login page at dangnhap.html:

![image](https://github.com/TaiTitans/TaiTitans.github.io/assets/70010376/7a7f1a5e-b3f2-4b70-bf1f-e9c91748e62a)

**Comment by nhuttran02** [comment]
Can you assign me this issue?

**Comment by TaiTitans** [comment]
> Can you assign me this issue?

Okay i accept for you

**Comment by ngoc1230321** [comment]
Can you assign me ?

**Comment by TaiTitans** [comment]
> Can you assign me ?

Go to https://github.com/TaiTitans/porscher_website/issues/3 and if you want . i will accept you .
